### ISSUE TITLE
Error Execute

### ISSUE THREAD

**Issue by maxhunter1990** [kleiton0x00/XSScope#14]
When I execute get this error : 
python3 xsscope.py
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "xsscope.py", line 1244, in main
    root_main = tk.Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
[Mon Apr 10 13:48:06 2023] PHP 8.1.17 Development Server (http://localhost:1337) started

**Comment by kleiton0x00** [comment]
Make sure to first install `php`.

`sudo apt-get install php`

**Comment by maxhunter1990** [comment]
> Make sure to first install `php`.
> 
> `sudo apt-get install php`

It doesnt work ,I have installed this befor 
PHP 8.1.17 (cli) (built: Mar 16 2023 14:37:57) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.17, Copyright (c), by Zend Technologies

**Comment by maxhunter1990** [comment]
?
